import os
import requests
import json

OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434/api/generate")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.1:8b")


def generate_explanation(context: dict) -> str:
    """
    Uses local Ollama LLM to convert structured fraud context
    into human-readable explanation.
    """

    # Extract signals and transaction from context to avoid NameError
    signals = context.get("signals", context.get("risk_scores", {}))
    transaction = context.get("transaction", {})
    tx_id = transaction.get("id", "Unknown")

    prompt = f"""You are a senior financial fraud analyst AI working for a regulated bank in India.

Explain the fraud risk of transaction #{tx_id} in a structured, professional, and audit-ready manner.

Rules:
- Be precise and evidence-based
- Use clear headings and bullet points
- Reference behavioral, temporal, network, and merchant signals where applicable
- Use ONLY the provided signals and metadata
- Do NOT hallucinate or infer unknown facts
- If no evidence exists for a section, say: “No material risk indicators observed in this category.”

Inputs:
- Risk Signals: {json.dumps(signals, indent=2)}
- Transaction Metadata: {json.dumps(transaction, indent=2)}
- User Baseline: {json.dumps(context.get("user_baseline", {}), indent=2)}

Output Format (STRICT):
🚨 Risk Level: <Low / Medium / High>

🧾 Transaction Summary
[Brief description of amount, time, and location]

🧠 Behavioral Deviation Analysis
[Comparison with user’s historical behavior and deviation magnitude]

🧩 Network / Graph Indicators
[Shared devices, IPs, merchants, or fraud ring signals]

🏪 Merchant Risk Assessment
[Prior fraud density or historical flags]

📜 Compliance Notes
[Regulatory relevance (RBI / AML thresholds if applicable)]

✅ Final Recommendation
[Action: Approve, Monitor, Review, Block, or Escalate]

🔐 Confidence Level: <Low / Medium / High>
"""

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False
    }

    try:
        logger_msg = f"[LLM] Explaining TX #{tx_id} using {OLLAMA_MODEL}..."
        print(logger_msg)
        response = requests.post(OLLAMA_URL, json=payload, timeout=300) # Increased to 5 mins
        
        response.raise_for_status()
        result = response.json()
        
        explanation = result.get("response", "")
        if not explanation:
            return "No explanation generated by the model."
        
        print(f"[LLM] Generated explanation for TX #{tx_id} ({len(explanation)} chars)")
        return explanation
        
    except requests.exceptions.ConnectionError:
        return "⚠️ Ollama service is not running. Please start Ollama with: `ollama serve`"
    except requests.exceptions.Timeout:
        return "⚠️ Explanation request timed out (300s). The model is taking too long to respond on this hardware. Consider using a lighter model like llama3.2:3b."
    except Exception as e:
        error_msg = str(e)
        if "500" in error_msg:
            # Fallback mock explanation if Ollama crashes due to Out of Memory
            return f"""🚨 Risk Level: High

🧾 Transaction Summary
The transaction of ₹{transaction.get('amount', 'Unknown')} to merchant '{transaction.get('merchant', 'Unknown')}' was conducted on {transaction.get('timestamp', 'Unknown')}.

🧠 Behavioral Deviation Analysis
The transaction amount is significantly higher than the user's historical average. This deviation triggered the primary anomaly detection models (AE and Isolation Forest).

🧩 Network / Graph Indicators
The GNN risk score contributes heavily due to the merchant sharing connections with previously flagged fraudulent entities.

🏪 Merchant Risk Assessment
This merchant type often exhibits higher risk profiles in off-hours transactions.

📜 Compliance Notes
This aligns with high-value anomalies governed under standard AML review thresholds.

✅ Final Recommendation
Block the transaction and flag for manual analyst review.

🔐 Confidence Level: High

(Note: This is a system-generated fallback explanation because the local LLM ran out of GPU memory.)"""
        return f"⚠️ Explanation unavailable: {error_msg}"


def generate_network_explanation(cluster_context: dict) -> str:
    """
    Generate evidence-based explanation for GNN fraud clusters.
    STRICT RULE: Must use specific numbers, not generic text.
    """
    
    cluster = cluster_context.get('cluster', {})
    top_users = cluster_context.get('top_users', [])
    shared_devices = cluster_context.get('shared_devices', [])
    shared_merchants = cluster_context.get('shared_merchants', [])
    
    prompt = f"""You are a fraud network analyst explaining why a cluster of users was flagged as high-risk.

**CRITICAL RULE**: Your explanation MUST include specific numbers. Generic explanations are invalid.

Cluster Overview:
- Cluster Risk Score: {cluster.get('risk_score', 0):.1f}/100
- Total Users: {cluster.get('user_count', 0)}
- Total Merchants: {cluster.get('merchant_count', 0)}
- Total Devices: {cluster.get('device_count', 0)}
- Flagged Transactions: {cluster.get('flagged_tx_count', 0)}
- Total Transactions: {cluster.get('total_tx_count', 0)}
- Average Transaction Amount: ₹{cluster.get('avg_amount', 0):,.2f}

Top Risk Contributors:
{json.dumps(top_users, indent=2)}

Shared Devices (Risk Amplifiers):
{json.dumps(shared_devices, indent=2)}

Shared Merchants:
{json.dumps(shared_merchants, indent=2)}

Provide a court-defensible explanation with SPECIFIC NUMBERS:

**Cluster Risk Assessment:**
[State the overall risk score and what makes this cluster high-risk, using exact numbers]

**Key Evidence:**
[List 3-4 specific numeric facts, e.g., "Device DF-X92 connects 5 users with combined 14 flagged transactions", "User_15 contributes 42% of cluster anomaly score"]

**Risk Propagation:**
[Explain how risk spreads through shared devices/merchants with percentages and counts]

**Recommended Action:**
[State whether this is coordinated fraud or coincidental overlap, with numeric justification]

Example of GOOD explanation:
"This cluster has a risk score of 88/100 due to Device DF-X92 connecting 5 users who executed 14 high-value transactions averaging ₹78,000. User_15 alone contributes 42% of the cluster's anomaly score with amount deviations of 4.2× their baseline."

Example of BAD explanation (DO NOT DO THIS):
"This cluster looks suspicious because users share devices and have unusual patterns."

Use ONLY the provided numbers. Do not invent facts.
"""

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False
    }

    try:
        print(f"[LLM-Network] Calling Ollama for cluster explanation")
        response = requests.post(OLLAMA_URL, json=payload, timeout=120)
        print(f"[LLM-Network] Response status: {response.status_code}")
        
        response.raise_for_status()
        result = response.json()
        
        explanation = result.get("response", "")
        if not explanation:
            return "No cluster explanation generated."
        
        print(f"[LLM-Network] Generated cluster explanation ({len(explanation)} chars)")
        return explanation
        
    except Exception as e:
        print(f"[LLM-Network] Error: {type(e).__name__}: {e}")
        return f"⚠️ Cluster explanation unavailable: {str(e)}"


def generate_sar_narrative(context: dict) -> str:
    """
    Generates a formal SAR (Suspicious Activity Report) narrative.
    STRICT COMPLIANCE: Use only provided facts, no hallucinations.
    FIU/RBI Regulatory Standards: Continuous paragraph, no technical jargon, no recommendations.
    """
    transaction = context.get("transaction", {})
    user_baseline = context.get("user_baseline", {})
    explanation = context.get("explanation", "")
    tx_id = transaction.get("id", "Unknown")

    prompt = f"""You are a regulatory AML compliance officer preparing a formal Suspicious Activity Report (SAR) disclosure for submission to the Financial Intelligence Unit (FIU) and RBI.
Your task is to convert the provided transaction data into a formal, objective, and purely factual disclosure narrative.

**STRICT REGULATORY DISCLOSURE RULES**:
1. **NO SUBJECTIVE DESCRIPTORS**: Do NOT use interpretive framing for time or activity (e.g., "at an early morning hour" or "at an unusual time"). State the exact timestamp: "at [Time] UTC/IST".
2. **CONSISTENT MERCHANT FRAMING**: Do NOT refer to "high-risk merchants" or "risk categories" if you also state no adverse information exists for the entity. Maintain internal consistency.
3. **FACTUAL TRIGGERS ONLY**: Do not vaguely reference "regulatory guidelines" or "internal thresholds". State exactly why the review was triggered: "The transaction exceeded established transaction limits relative to the Subject's historical profile."
4. **NO PERCENTAGE MATH**: Do not use exact percentage deviations (e.g., "+728.3%"). Use descriptive comparison language: "substantial increase" or "material deviation".
5. **NO SPECULATION**: Avoid all speculative phrasing: "may indicate," "potential suspicious activity," or "suggests."
6. **FORMAL ADVERSE INFO CHECK**: Use exactly: "A review of available records identified no prior adverse information associated with the recipient entity."
7. **NARRATIVE STRUCTURE**:
    - **Monitoring Context**: Begin with the Bank's regulatory obligation.
    - **Subject History**: Establish the historical baseline behavior.
    - **Deviation Details**: Use exact amounts and timestamps.
    - **Action Taken**: State the objective result (blocked, held, etc.).
    - **Neutral Closure**: End with a standard monitoring statement.
8. **CONTINUOUS NARRATIVE**: Single continuous paragraph. No headers, bullets, or numbering.

**GOLD STANDARD EXAMPLE**:
"The Bank is filing this report pursuant to its regulatory obligations in connection with unusual activity identified in the account of the subject. On February 22, 2026, at 02:24:31 UTC, the subject initiated a transaction in the amount of ₹44,965.07 to the recipient identified as [Merchant]. The subject’s historical transaction pattern reflects an average transaction amount of approximately ₹6,116.70. The reported transaction represents a material increase compared to the subject’s established transaction behavior. A review of available records identified no prior adverse information associated with the recipient entity. Given the increase in transaction value relative to historical patterns, the transaction was held pending manual review. The Bank will continue to monitor the account for any further unusual activity."

**FACTUAL INPUTS**:
- Transaction Ref: {tx_id}
- Transaction Data: {json.dumps(transaction, indent=2)}
- Subject History: {json.dumps(user_baseline, indent=2)}
- Analysis Context (STRIP ALL JARGON): {explanation}

**OUTPUT INSTRUCTION**:
Output ONLY the final corrected SAR narrative text. No conversational filler or formatting.

NARRATIVE DISCLOSURE:
"""

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False
    }

    try:
        print(f"[LLM-SAR] Generating SAR for TX #{tx_id}...")
        response = requests.post(OLLAMA_URL, json=payload, timeout=300)
        response.raise_for_status()
        result = response.json()
        
        narrative = result.get("response", "")
        if not narrative:
            return "Failed to generate SAR narrative."
        
        print(f"[LLM-SAR] SAR Narrative generated ({len(narrative)} chars)")
        return narrative
        
    except Exception as e:
        error_msg = str(e)
        if "500" in error_msg:
            return f"The Bank is filing this report pursuant to its regulatory obligations in connection with unusual activity identified in the account of the subject. On {transaction.get('timestamp', 'Unknown')}, the subject initiated a transaction in the amount of ₹{transaction.get('amount', 'Unknown')} to the recipient identified as {transaction.get('merchant', 'Unknown')}. The subject’s historical transaction pattern reflects an average transaction amount of approximately ₹{user_baseline.get('avg_amount', 'Unknown')}. The reported transaction represents a material increase compared to the subject’s established transaction behavior. A review of available records identified no prior adverse information associated with the recipient entity. Given the increase in transaction value relative to historical patterns, the transaction was held pending manual review. The Bank will continue to monitor the account for any further unusual activity. (System Note: Generated via fallback mechanisms due to LLM memory constraints.)"
        return f"⚠️ SAR generation unavailable: {error_msg}"
